name: SonarCloud Analysis

on: pull_request

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - run: mvn clean verify

      - run: mvn sonar:sonar 
          -Dsonar.projectKey=githubactionsv123 
          -Dsonar.organization=githubactionsv123 
          -Dsonar.host.url=https://sonarcloud.io 
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} 
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
